### ISSUE TITLE
a question about the driver

### ISSUE THREAD

**Issue by Hollow-cat** [uglide/autopilot-qt#3]
Hello @uglide. I am looking for the GUI test tool for the qt application.I have found that there was a tool called the testability driver(T driver) from Nokia. 
But it was difficult to get the document and example of  T driver. So I searched the github and found your project. It was so nice and I also was appreciative of your help. 
I am not good at coding and I want to konw if the T driver of Nokia uses the same principle of your project.

**Comment by Hollow-cat** [comment]
I learn about that the communication  between the test script and the application is based on QtDBus. Can it be used in two different machines? For example,I want to run the script on one machine and the application is tested over the network on another machine.

**Comment by uglide** [comment]
@Hollow-cat It's possible to connect to dbus-daemon over TCP in local network https://stackoverflow.com/questions/10158684/connecting-to-dbus-over-tcp
